server:
  port: 80

eureka:
  instance:
    #实例名字
    instance-id: cloud-order-openfeign-consumer80
  client:
    service-url:
      #单机eureka地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://192.168.10.100:7001/eureka/,http://localhost:7002/eureka/

spring:
  application:
    name: cloud-server-consumer

logging:
  level:
    com.itbaizhan.service: debug

feign:
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 2000
